services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_BUILDKIT=1
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - REPO_NAME=drinks-touch
  - REPO_USER=flipdot
  - secure: Ds7lgK3vrqAaGeScoj8hq+MzRr/Wb0CV63jIEk6gjMC3qbpP4Ce7Rtl2HOM98bqS/gHdOlWMZMQHKY5N2MZRlj6JfJ4NN0HB08q/MI9xLSRn7+/pxk90+6egwYZ3RNcuhiQNy57xbGsLhNiinCX7e4lVYnc4C02fUi6XG00fBjYqox10+KPfBTrjmwmI6/7LBiUyx3VnoflKU11fETYUk+4PFLl85x/VBlcqxGoCbUz30AlkM6Nyv06H9ps3RfZE25LrIOgfRzFOEZ9UqVfpGdW2Xo9sjZHD17wibOYWW8FRHFDPjDyRUwjijpOivhErP6EOYpxnS6I+fo2GYHnR6Ot32FXFZZoHPNmnWVM7p//KH5ushhQlsz+vCqO6ljpIiIZIKwT129ioNUdyJHm2i7PR7wyLFFsFg5A97FBbQNy6soCbzHXKV84+p7I372tFJuH77RwIm1SMEtnxdz1YHe0caHVwgl+ukQggXYUQJXB6NZcsEQmDCwfh9ltk/YKMoHcBQ6WRpz3GAjfbiR+zSZfqFtefKLotsE0dYwZHXX73lkE2xM0w1WfepCQPzATc5MVwMWKoHtC0ysUh7dENFMEuNW8eGCZoxbw5/A+k9Zdn8f4ohWGCRJwiWO8t8AZAvSs85jBFztI0g3c66uNsq57dw5hl1lrujSyFE4IWdlc= #DOCKER_USER
  - secure: AWHet97pFQfGiJKklzCBXPurgsrI8BFInQu3lfeqJyioRNoixK695Adkpa/J9yfyItU9LP1q8qdi2wusDJkGCRIO6ijoa4wxpEAbtS1iChcJJTnMSbKgBGF4IduFTygfXgiTttfUDrAHdx6fPegAumJoJsySXOCYqw5XNiLfwqAUtsw8IPzWkSAAT1FG89UCRNZcU4LVvjPNAF7dtmonBwdBoNhZY5TmvdXIWIkea0Gy0VFpoObSr/vjuqNvi2KabEIdBZ+qKez7BpOsUKxC9ISqJuc7unOQZdlyAuC8X9ECobp7KQJdRM6LjOccWVob5T1v4ndv9J5BmiUtFXod1v8hQrMee2CHEOiwxNKHdJq6Rf8r2Tyd8sl0Fw/42JC10wIKJ7GtsXpVki5Yu9Ed95yvIIOXgO6av5o6+LHJVGEg2eTbiPBzmEFYnn7AMBALEeeZPFE7nvOcx0zhR2TCWIpLhW3XDjePWsxMOP1JLMKoFDmkZAUtoe1cslU1+25ZHew7YgjZwizaYfYknKQdrLwzhaobWNkNmKo6gNnsUnsoCrI7ZvWToKqiwGjn3X65MsO2Gn0czcYaIV/FSWNKRvIDhkF9A6aVKN+9pvjmfP4ZX8McV+pKud7S+pITgw0YKc7VcTryGPqyhv3cxGkA9SGUGbXXsw0QtVtrnA0EUDs= #DOCKER_PASS
before_install:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
script:
- travis_wait 60 docker buildx build --cache-from=$REPO_USER/$REPO_NAME:cache --cache-to=$REPO_USER/$REPO_NAME:cache --platform linux/amd64,linux/arm/v7 --push -t $REPO_USER/$REPO_NAME:$COMMIT .
after_success:
- docker tag $REPO_USER/$REPO_NAME:$COMMIT $REPO_USER/$REPO_NAME:$TAG
- docker push $REPO_USER/$REPO_NAME
